/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rs.malkier.bankarskisistem;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import rs.malkier.bankarskisistem.domain.Racun;
import rs.malkier.bankarskisistem.exception.KonverzijaException;
import rs.malkier.bankarskisistem.kontroler.Kontroler;



/**
 *
 * @author Pedja
 */
public class ConversionForm extends javax.swing.JDialog {
    
    List<Racun> racuni;

    /**
     * Creates new form ConversionForm
     * @param racuni
     */
    public ConversionForm(List<Racun> racuni) {
        setModal(true);
        initComponents();
        setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        this.racuni = racuni;
                
        for(Racun r : racuni){
            cmbRacunZaPrijem.addItem(r);
            cmbRacunZaSlanje.addItem(r);
        }

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOdabirRacunaZaSlanje = new javax.swing.JLabel();
        cmbRacunZaSlanje = new javax.swing.JComboBox<>();
        lblRacunZaPrijem = new javax.swing.JLabel();
        cmbRacunZaPrijem = new javax.swing.JComboBox<>();
        lblIznos = new javax.swing.JLabel();
        txtIznos = new javax.swing.JTextField();
        btnKonverzija = new javax.swing.JButton();

        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblOdabirRacunaZaSlanje.setText("Odaberi racun sa kog se salje");

        cmbRacunZaSlanje.setModel(new javax.swing.DefaultComboBoxModel<>(new Racun[] {}));

        lblRacunZaPrijem.setText("Odabir racuna na koji se salje");

        cmbRacunZaPrijem.setModel(new javax.swing.DefaultComboBoxModel<>(new Racun[] {}));

        lblIznos.setText("Iznos za konverziju");

        btnKonverzija.setText("Konverzija");
        btnKonverzija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonverzijaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblRacunZaPrijem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblOdabirRacunaZaSlanje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblIznos))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbRacunZaSlanje, 0, 159, Short.MAX_VALUE)
                            .addComponent(cmbRacunZaPrijem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIznos)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnKonverzija)
                        .addGap(0, 137, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOdabirRacunaZaSlanje)
                    .addComponent(cmbRacunZaSlanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRacunZaPrijem)
                    .addComponent(cmbRacunZaPrijem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIznos)
                    .addComponent(txtIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnKonverzija)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKonverzijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonverzijaActionPerformed

        try {
            boolean uspeh = Kontroler.getInstance()
                    .konvertuj((Racun) cmbRacunZaPrijem.getSelectedItem(),
                            (Racun) cmbRacunZaSlanje.getSelectedItem(),
                            Float.parseFloat(txtIznos.getText()));
            JOptionPane.showMessageDialog(this, "Uspesna konverzija");
            dispose();
        } catch (KonverzijaException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
    }//GEN-LAST:event_btnKonverzijaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKonverzija;
    private javax.swing.JComboBox<Racun> cmbRacunZaPrijem;
    private javax.swing.JComboBox<Racun> cmbRacunZaSlanje;
    private javax.swing.JLabel lblIznos;
    private javax.swing.JLabel lblOdabirRacunaZaSlanje;
    private javax.swing.JLabel lblRacunZaPrijem;
    private javax.swing.JTextField txtIznos;
    // End of variables declaration//GEN-END:variables
}
